"""empty message

Revision ID: 097dd80e3c67
Revises: df3284bcfde7
Create Date: 2022-03-08 15:47:23.935801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097dd80e3c67'
down_revision = 'df3284bcfde7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('shared', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'shared')
    # ### end Alembic commands ###
